export interface WeaponItemData {
  id: string;
  name: string;
  type: string;
  rarity: number;
  refinement: number;
  level: number;
  maxLevel: number;
  baseAtk: number;
  subStatName: string;
  subStatValue: string;
  passiveName: string;
  passiveDesc: string;
  description: string;
  svgPath: string;
  isEquipped?: boolean;
  isLocked?: boolean;
}

export const WEAPONS_DATA: WeaponItemData[] = [
  {
    "id": "c",
    "name": "C",
    "type": "Language",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Hardware Access",
    "subStatValue": "41.3%",
    "passiveName": "Foundation Language",
    "passiveDesc": "Direct system call access grants unmatched efficiency.",
    "description": "The mother of modern programming languages, foundational to operating systems and kernels.",
    "svgPath": "/assets/images/svg-tech/c-original.svg"
  },
  {
    "id": "csharp",
    "name": "C#",
    "type": "Language",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": ".NET Core",
    "subStatValue": "41.3%",
    "passiveName": "Garbage Collection",
    "passiveDesc": "Automatically reclaims unused memory during intense computations.",
    "description": "A versatile object-oriented language developed by Microsoft for enterprise and game development.",
    "svgPath": "/assets/images/svg-tech/csharp-original.svg"
  },
  {
    "id": "cplusplus",
    "name": "C++",
    "type": "Language",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Raw Performance",
    "subStatValue": "49.6%",
    "passiveName": "Manual Memory Control",
    "passiveDesc": "Direct pointer manipulation increases execution speed by 120%.",
    "description": "A legendary high-performance language crafted for low-level systems and graphics engines.",
    "svgPath": "/assets/images/svg-tech/cplusplus-original.svg"
  },
  {
    "id": "css3",
    "name": "CSS3",
    "type": "Language",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Style Mastery",
    "subStatValue": "55.1%",
    "passiveName": "Flexbox & Grid Alignment",
    "passiveDesc": "Mastery over layouts grants pixel-perfect responsive design capabilities.",
    "description": "The core styling language of the web, responsible for visual layouts, keyframe animations, and themes.",
    "svgPath": "/assets/images/svg-tech/css3-original.svg"
  },
  {
    "id": "dart",
    "name": "Dart",
    "type": "Language",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Sound Null Safety",
    "subStatValue": "49.6%",
    "passiveName": "AOT Compilation",
    "passiveDesc": "Compiles directly to fast native machine code for mobile and desktop apps.",
    "description": "A client-optimized programming language developed by Google for fast multi-platform apps.",
    "svgPath": "/assets/images/svg-tech/dart-original.svg"
  },
  {
    "id": "go",
    "name": "Go (Golang)",
    "type": "Language",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Goroutine Concurrency",
    "subStatValue": "44.1%",
    "passiveName": "Lightweight Threads",
    "passiveDesc": "Executes millions of concurrent goroutines with minimal memory overhead.",
    "description": "An open-source programming language designed at Google for fast, reliable, and efficient software.",
    "svgPath": "/assets/images/svg-tech/go-original-wordmark.svg"
  },
  {
    "id": "html5",
    "name": "HTML5",
    "type": "Language",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "DOM Structure",
    "subStatValue": "55.1%",
    "passiveName": "Semantic Markup",
    "passiveDesc": "Provides structural foundation and accessible DOM element parsing.",
    "description": "The standard markup language for documents designed to be displayed in web browsers.",
    "svgPath": "/assets/images/svg-tech/html5-original.svg"
  },
  {
    "id": "java",
    "name": "Java",
    "type": "Language",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "JVM Portability",
    "subStatValue": "55.1%",
    "passiveName": "Write Once Run Anywhere",
    "passiveDesc": "Cross-platform compatibility protects against environment vulnerabilities.",
    "description": "A battle-tested enterprise language running on billions of devices worldwide.",
    "svgPath": "/assets/images/svg-tech/java-original.svg",
    "isEquipped": true
  },
  {
    "id": "javascript",
    "name": "JavaScript",
    "type": "Language",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Event Loop",
    "subStatValue": "55.1%",
    "passiveName": "Async Concurrency",
    "passiveDesc": "Non-blocking I/O operations grant non-stop execution speed.",
    "description": "The ancient web scripting language powering dynamic interactions across all browser realms.",
    "svgPath": "/assets/images/svg-tech/javascript-original.svg"
  },
  {
    "id": "kotlin",
    "name": "Kotlin",
    "type": "Language",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Android Native",
    "subStatValue": "55.1%",
    "passiveName": "Coroutine Concurrency",
    "passiveDesc": "Concise syntax and built-in null safety streamline Android application development.",
    "description": "A modern, cross-platform, statically typed programming language with type inference.",
    "svgPath": "/assets/images/svg-tech/kotlin-original.svg"
  },
  {
    "id": "lua",
    "name": "Lua",
    "type": "Language",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Embeddable Scripting",
    "subStatValue": "55.1%",
    "passiveName": "Lightweight JIT",
    "passiveDesc": "Ultra-fast embeddable scripting engine for game engines and embedded systems.",
    "description": "A powerful, efficient, lightweight, embeddable scripting language.",
    "svgPath": "/assets/images/svg-tech/lua-original.svg"
  },
  {
    "id": "markdown",
    "name": "Markdown",
    "type": "Language",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Plain Text Syntax",
    "subStatValue": "55.1%",
    "passiveName": "Instant Parsing",
    "passiveDesc": "Converts human-readable plain text markup into rich HTML documents effortlessly.",
    "description": "A lightweight markup language for creating formatted text using a plain-text editor.",
    "svgPath": "/assets/images/svg-tech/markdown-original.svg"
  },
  {
    "id": "matlab",
    "name": "MATLAB",
    "type": "Language",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Matrix Computing",
    "subStatValue": "41.3%",
    "passiveName": "Numerical Simulation",
    "passiveDesc": "High-performance matrix math computations and algorithmic signal processing.",
    "description": "A programming and numeric computing platform used to analyze data and develop algorithms.",
    "svgPath": "/assets/images/svg-tech/matlab-original.svg"
  },
  {
    "id": "objectivec",
    "name": "Objective-C",
    "type": "Language",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Cocoa Runtime",
    "subStatValue": "41.3%",
    "passiveName": "Dynamic Messaging",
    "passiveDesc": "Smalltalk-style messaging layer built atop standard C for legacy Apple platforms.",
    "description": "The primary programming language used for Apple macOS and iOS development before Swift.",
    "svgPath": "/assets/images/svg-tech/objectivec-plain.svg"
  },
  {
    "id": "perl",
    "name": "Perl",
    "type": "Language",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Regex Parsing",
    "subStatValue": "41.3%",
    "passiveName": "Text Processing Engine",
    "passiveDesc": "Unmatched regular expression text manipulation for system administration scripts.",
    "description": "A highly capable, feature-rich programming language with over 30 years of development.",
    "svgPath": "/assets/images/svg-tech/perl-original.svg"
  },
  {
    "id": "php",
    "name": "PHP",
    "type": "Language",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Server Side",
    "subStatValue": "55.1%",
    "passiveName": "Hypertext Preprocessor",
    "passiveDesc": "Processes web page templates rapidly for dynamic web delivery.",
    "description": "A web server scripting language powering a massive portion of the world wide web.",
    "svgPath": "/assets/images/svg-tech/php-original.svg"
  },
  {
    "id": "python",
    "name": "Python",
    "type": "Language",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Data Science",
    "subStatValue": "66.2%",
    "passiveName": "Syntax Elegance",
    "passiveDesc": "Readability boosted by 100%. Accelerates prototyping speed.",
    "description": "An expressive high-level language revered for AI, machine learning, and rapid development.",
    "svgPath": "/assets/images/svg-tech/python-original.svg"
  },
  {
    "id": "ruby",
    "name": "Ruby",
    "type": "Language",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Developer Happiness",
    "subStatValue": "49.6%",
    "passiveName": "Object Metaprogramming",
    "passiveDesc": "Dynamic object-oriented programming language designed for natural readability.",
    "description": "A dynamic, open-source programming language with a focus on simplicity and productivity.",
    "svgPath": "/assets/images/svg-tech/ruby-plain.svg"
  },
  {
    "id": "rust",
    "name": "Rust",
    "type": "Language",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Borrow Checker",
    "subStatValue": "44.1%",
    "passiveName": "Zero-Cost Abstractions",
    "passiveDesc": "Memory safety without garbage collection ensures zero data races and maximum speed.",
    "description": "A language empowering everyone to build reliable and efficient software.",
    "svgPath": "/assets/images/svg-tech/rust-original.svg"
  },
  {
    "id": "typescript",
    "name": "TypeScript",
    "type": "Language",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Type Safety",
    "subStatValue": "44.1%",
    "passiveName": "Strict Type System",
    "passiveDesc": "Eliminates 95% of runtime TypeError bugs before compilation.",
    "description": "A strongly typed programming language built on JavaScript, giving developers total control over code integrity.",
    "svgPath": "/assets/images/svg-tech/typescript-original.svg"
  },
  {
    "id": "visualbasic",
    "name": "Visual Basic",
    "type": "Language",
    "rarity": 3,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 354,
    "subStatName": "RAD Event Model",
    "subStatValue": "28.0%",
    "passiveName": "Rapid Application Development",
    "passiveDesc": "Drag-and-drop form creation and event-driven programming model.",
    "description": "Legacy third-generation event-driven programming language from Microsoft.",
    "svgPath": "/assets/images/svg-tech/visualbasic-original.svg"
  },
  {
    "id": "dotnetcore",
    "name": ".NET Core",
    "type": "Framework",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Cross-Platform CLR",
    "subStatValue": "44.1%",
    "passiveName": "High Throughput API",
    "passiveDesc": "Ultra-fast web API execution and cloud-native microservice architecture.",
    "description": "A open-source, cross-platform successor to .NET for cloud-native web services.",
    "svgPath": "/assets/images/svg-tech/dotnetcore-original.svg"
  },
  {
    "id": "dot-net",
    "name": ".NET Framework",
    "type": "Framework",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "CLR Execution",
    "subStatValue": "41.3%",
    "passiveName": "Managed Code Runtime",
    "passiveDesc": "Provides memory management, security profiling, and language interoperability.",
    "description": "Microsoft’s legacy enterprise software development framework for Windows.",
    "svgPath": "/assets/images/svg-tech/dot-net-original.svg"
  },
  {
    "id": "angular",
    "name": "Angular",
    "type": "Framework",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "RxJS Stream",
    "subStatValue": "45.9%",
    "passiveName": "Two-Way Binding",
    "passiveDesc": "Synchronizes view and model state automatically across complex application trees.",
    "description": "A robust TypeScript web framework developed by Google for enterprise single-page applications.",
    "svgPath": "/assets/images/svg-tech/angular-original.svg"
  },
  {
    "id": "bootstrap",
    "name": "Bootstrap",
    "type": "Framework",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "12-Column Grid",
    "subStatValue": "55.1%",
    "passiveName": "Pre-styled UI Components",
    "passiveDesc": "Accelerates UI wireframing with ready-to-use responsive CSS components.",
    "description": "A powerful, feature-packed frontend toolkit for fast mobile-first web layout design.",
    "svgPath": "/assets/images/svg-tech/bootstrap-original.svg"
  },
  {
    "id": "codeigniter",
    "name": "CodeIgniter",
    "type": "Framework",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "MVC Footprint",
    "subStatValue": "36.8%",
    "passiveName": "Lightweight PHP Routing",
    "passiveDesc": "Delivers high-performance server routing with minimal configuration overhead.",
    "description": "A powerful PHP framework with a tiny footprint for building full-featured web apps.",
    "svgPath": "/assets/images/svg-tech/codeigniter-plain.svg"
  },
  {
    "id": "django",
    "name": "Django",
    "type": "Framework",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Python ORM",
    "subStatValue": "49.6%",
    "passiveName": "Batteries Included",
    "passiveDesc": "Built-in authentication, admin panel, and ORM accelerate secure backend creation.",
    "description": "A high-level Python web framework that encourages rapid development and clean design.",
    "svgPath": "/assets/images/svg-tech/django-plain.svg"
  },
  {
    "id": "electron",
    "name": "Electron",
    "type": "Framework",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 542,
    "subStatName": "Chromium Bridge",
    "subStatValue": "66.2%",
    "passiveName": "Desktop IPC Bridge",
    "passiveDesc": "Build cross-platform desktop apps using web technologies like HTML, CSS, and JS.",
    "description": "A framework for creating native desktop applications using web technologies.",
    "svgPath": "/assets/images/svg-tech/electron-original.svg"
  },
  {
    "id": "express",
    "name": "Express.js",
    "type": "Framework",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "REST Middleware",
    "subStatValue": "55.1%",
    "passiveName": "Minimalist Server Routing",
    "passiveDesc": "High-speed HTTP routing and custom middleware pipeline execution.",
    "description": "A fast, unopinionated, minimalist web framework for Node.js backends.",
    "svgPath": "/assets/images/svg-tech/express-original.svg"
  },
  {
    "id": "flutter",
    "name": "Flutter",
    "type": "Framework",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Dart Engine",
    "subStatValue": "66.2%",
    "passiveName": "Hot Reload",
    "passiveDesc": "Compiles native ARM code instantly for smooth 60fps multi-platform rendering.",
    "description": "Google’s UI toolkit for building natively compiled applications for mobile, web, and desktop from a single codebase.",
    "svgPath": "/assets/images/svg-tech/flutter-original.svg"
  },
  {
    "id": "ionic",
    "name": "Ionic",
    "type": "Framework",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Web Components",
    "subStatValue": "55.1%",
    "passiveName": "Cross-Platform UI",
    "passiveDesc": "Deploys mobile apps to iOS and Android using web standards.",
    "description": "An open-source mobile UI toolkit for building high quality cross-platform apps.",
    "svgPath": "/assets/images/svg-tech/ionic-original.svg"
  },
  {
    "id": "laravel",
    "name": "Laravel",
    "type": "Framework",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 542,
    "subStatName": "Eloquent ORM",
    "subStatValue": "66.2%",
    "passiveName": "Artisan CLI Engine",
    "passiveDesc": "Expressive MVC syntax, database migrations, and blade template rendering.",
    "description": "A PHP web framework with expressive, elegant syntax.",
    "svgPath": "/assets/images/svg-tech/laravel-original.svg"
  },
  {
    "id": "nestjs",
    "name": "NestJS",
    "type": "Framework",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "TypeScript Microservices",
    "subStatValue": "55.1%",
    "passiveName": "Angular-Style DI Engine",
    "passiveDesc": "Scalable server-side architecture with built-in dependency injection and decorators.",
    "description": "A progressive Node.js framework for building efficient, reliable and scalable server-side applications.",
    "svgPath": "/assets/images/svg-tech/nestjs-original.svg"
  },
  {
    "id": "nextjs",
    "name": "Next.js",
    "type": "Framework",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Server Components",
    "subStatValue": "44.1%",
    "passiveName": "App Router Rendering",
    "passiveDesc": "Hybrid Server-Side Rendering (SSR) and Static Site Generation (SSG) for React.",
    "description": "The React framework for the web enabling server-rendered and static React applications.",
    "svgPath": "/assets/images/svg-tech/nextjs-original.svg"
  },
  {
    "id": "nuxtjs",
    "name": "Nuxt.js",
    "type": "Framework",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 542,
    "subStatName": "Vue SSR Engine",
    "subStatValue": "66.2%",
    "passiveName": "Nitro Server Engine",
    "passiveDesc": "Universal Vue.js web applications with auto-imported components and SSR routing.",
    "description": "The Intuitive Vue Framework for building full-stack web applications.",
    "svgPath": "/assets/images/svg-tech/nuxtjs-original.svg"
  },
  {
    "id": "qt",
    "name": "Qt",
    "type": "Framework",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Signals & Slots",
    "subStatValue": "45.9%",
    "passiveName": "Cross-Platform GUI",
    "passiveDesc": "Native C++ GUI widget rendering and QML reactive UI layout compilation.",
    "description": "A cross-platform software widget toolkit for creating graphical user interfaces.",
    "svgPath": "/assets/images/svg-tech/qt-original.svg"
  },
  {
    "id": "spring",
    "name": "Spring Boot",
    "type": "Framework",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Dependency Injection",
    "subStatValue": "49.6%",
    "passiveName": "Inversion of Control",
    "passiveDesc": "Auto-configuration streamlines microservice REST backend bootstrapping.",
    "description": "An enterprise Java framework used to build standalone, production-grade Spring applications.",
    "svgPath": "/assets/images/svg-tech/spring-original.svg"
  },
  {
    "id": "symfony",
    "name": "Symfony",
    "type": "Framework",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "PHP Components",
    "subStatValue": "41.3%",
    "passiveName": "Reusable HTTP Kernel",
    "passiveDesc": "A set of reusable PHP components and a web framework for enterprise builds.",
    "description": "A PHP framework and a set of reusable PHP components.",
    "svgPath": "/assets/images/svg-tech/symfony-original.svg"
  },
  {
    "id": "tailwindcss",
    "name": "Tailwind CSS",
    "type": "Framework",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 542,
    "subStatName": "Utility First",
    "subStatValue": "66.2%",
    "passiveName": "JIT Compilation",
    "passiveDesc": "Just-in-Time CSS engine purges unused styles for ultra-compact bundle size.",
    "description": "A utility-first CSS framework packed with classes for rapid custom UI building.",
    "svgPath": "/assets/images/svg-tech/tailwindcss-original.svg"
  },
  {
    "id": "vuejs",
    "name": "Vue.js",
    "type": "Framework",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 542,
    "subStatName": "Reactivity System",
    "subStatValue": "66.2%",
    "passiveName": "Single File Components",
    "passiveDesc": "Ref and reactive state tracking update virtual DOM nodes efficiently.",
    "description": "A progressive JavaScript framework for building user interfaces on the web.",
    "svgPath": "/assets/images/svg-tech/vuejs-original.svg"
  },
  {
    "id": "chartjs",
    "name": "Chart.js",
    "type": "Library",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Canvas Data Viz",
    "subStatValue": "41.3%",
    "passiveName": "Dynamic Rendering",
    "passiveDesc": "Renders responsive 2D HTML5 canvas charts dynamically from raw dataset streams.",
    "description": "Simple yet flexible JavaScript charting library for designers and developers.",
    "svgPath": "/assets/images/svg-tech/chartjs-original.svg"
  },
  {
    "id": "discordjs",
    "name": "Discord.js",
    "type": "Library",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "WebSocket Gateway",
    "subStatValue": "55.1%",
    "passiveName": "Bot Event Handling",
    "passiveDesc": "Interacts seamlessly with the Discord API for automated community interactions.",
    "description": "A powerful Node.js module that allows developers to interact easily with the Discord API.",
    "svgPath": "/assets/images/svg-tech/discordjs-original.svg"
  },
  {
    "id": "jquery",
    "name": "jQuery",
    "type": "Library",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "DOM Manipulation",
    "subStatValue": "55.1%",
    "passiveName": "AJAX Traversal",
    "passiveDesc": "Simplifies HTML document traversal, event handling, and animation.",
    "description": "A fast, small, and feature-rich JavaScript library.",
    "svgPath": "/assets/images/svg-tech/jquery-original-wordmark.svg"
  },
  {
    "id": "numpy",
    "name": "NumPy",
    "type": "Library",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "N-Dimensional Array",
    "subStatValue": "49.6%",
    "passiveName": "Vectorized Operations",
    "passiveDesc": "High-speed C-optimized array and matrix computations for Python data pipelines.",
    "description": "The fundamental package for scientific computing with Python.",
    "svgPath": "/assets/images/svg-tech/numpy-original.svg"
  },
  {
    "id": "opencv",
    "name": "OpenCV",
    "type": "Library",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Computer Vision",
    "subStatValue": "44.1%",
    "passiveName": "Real-time Image Matrix",
    "passiveDesc": "Real-time computer vision, object detection, and GPU-accelerated image processing.",
    "description": "An open-source computer vision and machine learning software library.",
    "svgPath": "/assets/images/svg-tech/opencv-original.svg"
  },
  {
    "id": "react",
    "name": "React",
    "type": "Library",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 542,
    "subStatName": "Component DMG",
    "subStatValue": "88.2%",
    "passiveName": "Virtual DOM Mastery",
    "passiveDesc": "Increases Render Efficiency by 80%. Re-renders occur 50% faster when state changes.",
    "description": "A component-based UI framework forged in Meta labs, capable of reactive UI rendering with unmatched precision.",
    "svgPath": "/assets/images/svg-tech/react-original.svg"
  },
  {
    "id": "thymeleaf",
    "name": "Thymeleaf",
    "type": "Library",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Natural Templates",
    "subStatValue": "36.8%",
    "passiveName": "Java Template Engine",
    "passiveDesc": "Modern server-side Java template engine for web and standalone environments.",
    "description": "A modern server-side Java template engine for both web and standalone environments.",
    "svgPath": "/assets/images/svg-tech/thymeleaf-original.svg"
  },
  {
    "id": "bun",
    "name": "Bun",
    "type": "Runtime",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Zig Performance",
    "subStatValue": "44.1%",
    "passiveName": "Ultra Fast Bundler",
    "passiveDesc": "Blazing-fast JavaScript runtime, package manager, and bundler all in one.",
    "description": "An incredibly fast JavaScript runtime built with Zig for modern server-side apps.",
    "svgPath": "/assets/images/svg-tech/bun-original.svg"
  },
  {
    "id": "nodejs-wordmark",
    "name": "Node.js Logo",
    "type": "Runtime",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "NPM Ecosystem",
    "subStatValue": "45.9%",
    "passiveName": "Module Resolution",
    "passiveDesc": "Instantly links package dependencies across server pipelines.",
    "description": "Node.js runtime badge featuring full wordmark branding.",
    "svgPath": "/assets/images/svg-tech/nodejs-original-wordmark.svg"
  },
  {
    "id": "godot",
    "name": "Godot",
    "type": "Engine",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Node System",
    "subStatValue": "69.0%",
    "passiveName": "Lightweight Architecture",
    "passiveDesc": "Open-source game engine nodes boost 2D and 3D scene creation.",
    "description": "A lightweight, feature-packed open-source engine designed for independent game developers.",
    "svgPath": "/assets/images/svg-tech/godot-original.svg"
  },
  {
    "id": "unity",
    "name": "Unity",
    "type": "Engine",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Cross Platform",
    "subStatValue": "49.6%",
    "passiveName": "Shader Graph",
    "passiveDesc": "Real-time rendering pipeline delivers rich visual graphics.",
    "description": "An industry-standard game development platform for mobile, console, and PC titles.",
    "svgPath": "/assets/images/svg-tech/unity-original.svg"
  },
  {
    "id": "unrealengine",
    "name": "Unreal Engine",
    "type": "Engine",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Nanite & Lumen",
    "subStatValue": "44.1%",
    "passiveName": "C++ Real-Time Photorealism",
    "passiveDesc": "Photorealistic real-time 3D graphics engine with Nanite virtualized geometry.",
    "description": "The world’s most open and advanced real-time 3D creation tool for photorealistic visuals.",
    "svgPath": "/assets/images/svg-tech/unrealengine-original.svg"
  },
  {
    "id": "mariadb",
    "name": "MariaDB",
    "type": "Database",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Aria Storage Engine",
    "subStatValue": "41.3%",
    "passiveName": "Open-Source RDBMS",
    "passiveDesc": "Drop-in MySQL replacement with improved query performance and storage engines.",
    "description": "One of the most popular open-source relational database servers.",
    "svgPath": "/assets/images/svg-tech/mariadb-original.svg"
  },
  {
    "id": "mongodb",
    "name": "MongoDB",
    "type": "Database",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "NoSQL BSON",
    "subStatValue": "49.6%",
    "passiveName": "Document Sharding",
    "passiveDesc": "Flexible schema document storage allows seamless dynamic scaling across server clusters.",
    "description": "A popular document-oriented NoSQL database designed for high availability and scalability.",
    "svgPath": "/assets/images/svg-tech/mongodb-original.svg"
  },
  {
    "id": "mysql-wordmark",
    "name": "MySQL",
    "type": "Database",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "SQL Queries",
    "subStatValue": "41.3%",
    "passiveName": "Indexed Lookup",
    "passiveDesc": "Accelerates join operations across complex relational tables.",
    "description": "MySQL database insignia with full brand wordmark.",
    "svgPath": "/assets/images/svg-tech/mysql-original-wordmark.svg"
  },
  {
    "id": "oracle",
    "name": "Oracle",
    "type": "Database",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Enterprise SQL",
    "subStatValue": "44.1%",
    "passiveName": "PL/SQL Execution",
    "passiveDesc": "High-availability data clustering and enterprise-grade security protocols.",
    "description": "A multi-model database management system designed for mission-critical enterprise workloads.",
    "svgPath": "/assets/images/svg-tech/oracle-original.svg"
  },
  {
    "id": "postgresql",
    "name": "PostgreSQL",
    "type": "Database",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "JSONB Indexing",
    "subStatValue": "49.6%",
    "passiveName": "Object-Relational Power",
    "passiveDesc": "Advanced indexing methods support complex spatial and document queries.",
    "description": "A powerful, open-source object-relational database system with a reputation for reliability.",
    "svgPath": "/assets/images/svg-tech/postgresql-original.svg"
  },
  {
    "id": "sqlite",
    "name": "SQLite",
    "type": "Database",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Embedded Engine",
    "subStatValue": "55.1%",
    "passiveName": "Zero-Configuration Storage",
    "passiveDesc": "Self-contained, serverless, transactional SQL database engine compiled directly into binaries.",
    "description": "A C-language library that implements a small, fast, self-contained SQL database engine.",
    "svgPath": "/assets/images/svg-tech/sqlite-original.svg"
  },
  {
    "id": "ansible",
    "name": "Ansible",
    "type": "DevOps",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Playbook Automation",
    "subStatValue": "45.9%",
    "passiveName": "Agentless Provisioning",
    "passiveDesc": "Automates IT infrastructure configuration and cloud deployment without remote agents.",
    "description": "An open-source IT automation engine that automates cloud provisioning and configuration management.",
    "svgPath": "/assets/images/svg-tech/ansible-original.svg"
  },
  {
    "id": "jenkins",
    "name": "Jenkins",
    "type": "DevOps",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "CI/CD Automation",
    "subStatValue": "55.1%",
    "passiveName": "Pipeline Scripting",
    "passiveDesc": "Automates building, testing, and deploying software continuously.",
    "description": "An open source automation server which enables developers around the world to reliably build, test, and deploy software.",
    "svgPath": "/assets/images/svg-tech/jenkins-original.svg"
  },
  {
    "id": "kubernetes",
    "name": "Kubernetes",
    "type": "DevOps",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Pod Orchestration",
    "subStatValue": "44.1%",
    "passiveName": "Automated Auto-Scaling",
    "passiveDesc": "Orchestrates container deployment, self-healing, and load balancing across clusters.",
    "description": "An open-source container orchestration system for automating application deployment, scaling, and management.",
    "svgPath": "/assets/images/svg-tech/kubernetes-original.svg"
  },
  {
    "id": "anaconda",
    "name": "Anaconda",
    "type": "Platform",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Conda Environment",
    "subStatValue": "41.3%",
    "passiveName": "Data Science Distribution",
    "passiveDesc": "Simplifies package management and deployment for Python and R data science workflows.",
    "description": "The world’s most popular data science platform for Python and R.",
    "svgPath": "/assets/images/svg-tech/anaconda-original.svg"
  },
  {
    "id": "codepen",
    "name": "CodePen",
    "type": "Platform",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Live Code Sandbox",
    "subStatValue": "36.8%",
    "passiveName": "Instant Pen Playground",
    "passiveDesc": "Front-end web development environment for testing HTML, CSS, and JS snippets in real-time.",
    "description": "A social development environment for front-end designers and developers.",
    "svgPath": "/assets/images/svg-tech/codepen-original.svg"
  },
  {
    "id": "github",
    "name": "GitHub",
    "type": "Platform",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Git Versioning",
    "subStatValue": "44.1%",
    "passiveName": "CI/CD Actions Flow",
    "passiveDesc": "Automates cloud builds, code reviews, and global open-source repository hosting.",
    "description": "The world’s leading developer platform for code hosting, version control, and collaboration.",
    "svgPath": "/assets/images/svg-tech/github-original.svg"
  },
  {
    "id": "gitlab",
    "name": "GitLab",
    "type": "Platform",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "DevOps Pipeline",
    "subStatValue": "49.6%",
    "passiveName": "Auto DevOps CI",
    "passiveDesc": "Integrates security scanning, code hosting, and automated deployment pipelines.",
    "description": "The complete DevOps platform delivered as a single application.",
    "svgPath": "/assets/images/svg-tech/gitlab-original.svg"
  },
  {
    "id": "heroku",
    "name": "Heroku",
    "type": "Platform",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Dyno Scaling",
    "subStatValue": "36.8%",
    "passiveName": "Git Push Deployment",
    "passiveDesc": "Instantly deploys web backends directly from git repository commits.",
    "description": "A cloud platform as a service (PaaS) supporting several programming languages.",
    "svgPath": "/assets/images/svg-tech/heroku-original.svg"
  },
  {
    "id": "netlify",
    "name": "Netlify",
    "type": "Platform",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "JAMstack Edge",
    "subStatValue": "55.1%",
    "passiveName": "Atomic Git Deploys",
    "passiveDesc": "Automated continuous deployment and instant edge-network static hosting.",
    "description": "A web development platform that multiplies productivity with automated workflows.",
    "svgPath": "/assets/images/svg-tech/netlify-original.svg"
  },
  {
    "id": "stackoverflow",
    "name": "Stack Overflow",
    "type": "Platform",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Community Wisdom",
    "subStatValue": "44.1%",
    "passiveName": "Reputation Upvotes",
    "passiveDesc": "Instant access to solutions for developer bugs, error tracebacks, and technical Q&A.",
    "description": "The largest, most trusted online community for developers to learn and share knowledge.",
    "svgPath": "/assets/images/svg-tech/stackoverflow-original.svg"
  },
  {
    "id": "vercel",
    "name": "Vercel",
    "type": "Platform",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Edge Network",
    "subStatValue": "55.1%",
    "passiveName": "Instant Frontend Cloud",
    "passiveDesc": "Zero-configuration deployments, global edge network, and serverless functions for web apps.",
    "description": "The Frontend Cloud platform for Next.js, React, and modern web frameworks.",
    "svgPath": "/assets/images/svg-tech/vercel-original.svg"
  },
  {
    "id": "maven",
    "name": "Apache Maven",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "POM Repository",
    "subStatValue": "41.3%",
    "passiveName": "Dependency Resolution",
    "passiveDesc": "Automates Java artifact builds and transitive dependency tree resolution.",
    "description": "A software project management and comprehension tool based on the concept of a POM.",
    "svgPath": "/assets/images/svg-tech/maven-plain.svg"
  },
  {
    "id": "blender",
    "name": "Blender",
    "type": "Tool",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "3D Sculpting",
    "subStatValue": "49.6%",
    "passiveName": "Cycles Render Engine",
    "passiveDesc": "Real-time ray tracing and mesh sculpting unleash creative visual fidelity.",
    "description": "An open-source 3D creation suite supporting modeling, rigging, animation, rendering, and compositing.",
    "svgPath": "/assets/images/svg-tech/blender-original.svg"
  },
  {
    "id": "cmake",
    "name": "CMake",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Build Generation",
    "subStatValue": "41.3%",
    "passiveName": "Cross-Platform Build",
    "passiveDesc": "Generates native build scripts across GCC, Clang, and MSVC platforms.",
    "description": "An open-source family of tools designed to build, test, and package C and C++ software.",
    "svgPath": "/assets/images/svg-tech/cmake-original.svg"
  },
  {
    "id": "docker",
    "name": "Docker",
    "type": "Tool",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Containerization",
    "subStatValue": "44.1%",
    "passiveName": "Isolated Environments",
    "passiveDesc": "Bundles code and dependencies into portable, isolated container images.",
    "description": "An open platform for developing, shipping, and running applications inside lightweight containers.",
    "svgPath": "/assets/images/svg-tech/docker-original.svg"
  },
  {
    "id": "eslint",
    "name": "ESLint",
    "type": "Tool",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "AST Analysis",
    "subStatValue": "55.1%",
    "passiveName": "Static Code Linting",
    "passiveDesc": "Enforces code style and catches syntax/logical bugs before runtime compilation.",
    "description": "A pluggable static analysis tool for identifying problematic patterns in JavaScript code.",
    "svgPath": "/assets/images/svg-tech/eslint-original.svg"
  },
  {
    "id": "filezilla",
    "name": "FileZilla",
    "type": "Tool",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "FTP Protocol",
    "subStatValue": "36.8%",
    "passiveName": "SFTP File Transfer",
    "passiveDesc": "Transfers website files securely to remote hosting servers.",
    "description": "A free, cross-platform FTP, FTPS and SFTP client with a clean GUI interface.",
    "svgPath": "/assets/images/svg-tech/filezilla-original.svg"
  },
  {
    "id": "gitkraken",
    "name": "GitKraken",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Branch Visualizer",
    "subStatValue": "41.3%",
    "passiveName": "Git Tree Graph",
    "passiveDesc": "Simplifies complex merge conflicts and branch rebase operations visually.",
    "description": "A powerful, intuitive, cross-platform GUI client for Git version control.",
    "svgPath": "/assets/images/svg-tech/gitkraken-original.svg"
  },
  {
    "id": "gradle",
    "name": "Gradle",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Build Cache",
    "subStatValue": "41.3%",
    "passiveName": "Incremental Compilation",
    "passiveDesc": "Accelerates Java and Android build times by reusing cached build outputs.",
    "description": "A build automation tool for multi-language software development.",
    "svgPath": "/assets/images/svg-tech/gradle-original.svg"
  },
  {
    "id": "jupyter",
    "name": "Jupyter",
    "type": "Tool",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Interactive Notebook",
    "subStatValue": "49.6%",
    "passiveName": "Markdown & Plot Execution",
    "passiveDesc": "Combines live code, equations, visualizations, and narrative text in interactive notebooks.",
    "description": "Free software, open standards, and web services for interactive computing across programming languages.",
    "svgPath": "/assets/images/svg-tech/jupyter-original.svg"
  },
  {
    "id": "latex",
    "name": "LaTeX",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Typesetting Engine",
    "subStatValue": "41.3%",
    "passiveName": "Mathematical Formatting",
    "passiveDesc": "Renders precise mathematical formulas and academic publication layouts.",
    "description": "A high-quality typesetting system designed for technical and scientific documentation.",
    "svgPath": "/assets/images/svg-tech/latex-original.svg"
  },
  {
    "id": "less",
    "name": "Less",
    "type": "Tool",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "CSS Preprocessor",
    "subStatValue": "36.8%",
    "passiveName": "Dynamic Stylesheet",
    "passiveDesc": "Extends CSS with variables, mixins, and operations for flexible styling.",
    "description": "A backward-compatible language extension for CSS.",
    "svgPath": "/assets/images/svg-tech/less-plain-wordmark.svg"
  },
  {
    "id": "ngrok",
    "name": "ngrok",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Secure Tunnels",
    "subStatValue": "41.3%",
    "passiveName": "Localhost Webhook Bridge",
    "passiveDesc": "Exposes local development web servers to the public internet securely.",
    "description": "A cross-platform ingress capability to expose local endpoints to the cloud.",
    "svgPath": "/assets/images/svg-tech/ngrok-original.svg"
  },
  {
    "id": "notion",
    "name": "Notion",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Workspace Knowledge",
    "subStatValue": "41.3%",
    "passiveName": "Modular Database Blocks",
    "passiveDesc": "Organizes notes, tasks, project roadmaps, and wiki documentation seamlessly.",
    "description": "An all-in-one workspace for your notes, tasks, wikis, and databases.",
    "svgPath": "/assets/images/svg-tech/notion-original.svg"
  },
  {
    "id": "npm",
    "name": "npm",
    "type": "Tool",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Package Registry",
    "subStatValue": "55.1%",
    "passiveName": "Semantic Versioning",
    "passiveDesc": "Manages JavaScript package dependencies and node module trees effortlessly.",
    "description": "The package manager for JavaScript and the world’s largest software registry.",
    "svgPath": "/assets/images/svg-tech/npm-original-wordmark.svg"
  },
  {
    "id": "pnpm",
    "name": "pnpm",
    "type": "Tool",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Hard-Linked Store",
    "subStatValue": "55.1%",
    "passiveName": "Content-Addressable Store",
    "passiveDesc": "Saves gigabytes of disk space using content-addressable hard links for node_modules.",
    "description": "Fast, disk space efficient package manager for JavaScript.",
    "svgPath": "/assets/images/svg-tech/pnpm-original.svg"
  },
  {
    "id": "postman",
    "name": "Postman",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "API Testing",
    "subStatValue": "41.3%",
    "passiveName": "Endpoint Automation",
    "passiveDesc": "Automates REST and GraphQL request testing and documentation generation.",
    "description": "An API platform for building, testing, and iterating on web endpoints.",
    "svgPath": "/assets/images/svg-tech/postman-original.svg"
  },
  {
    "id": "pytest",
    "name": "pytest",
    "type": "Tool",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Test Automation",
    "subStatValue": "55.1%",
    "passiveName": "Fixture Injection",
    "passiveDesc": "Simplifies writing small tests while scaling to support complex functional testing for Python.",
    "description": "A mature full-featured Python testing tool that helps you write better programs.",
    "svgPath": "/assets/images/svg-tech/pytest-original.svg"
  },
  {
    "id": "sass",
    "name": "Sass",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "SCSS Nesting",
    "subStatValue": "55.1%",
    "passiveName": "Mixin Generation",
    "passiveDesc": "Reusability mixins and CSS variables reduce stylesheet duplication by 60%.",
    "description": "A mature, stable, and powerful professional-grade CSS extension language.",
    "svgPath": "/assets/images/svg-tech/sass-original.svg"
  },
  {
    "id": "selenium",
    "name": "Selenium",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "WebDriver Engine",
    "subStatValue": "41.3%",
    "passiveName": "Browser Automation",
    "passiveDesc": "Automates web browsers for end-to-end user acceptance testing across platforms.",
    "description": "An umbrella project for a range of tools and libraries that enable and support web browser automation.",
    "svgPath": "/assets/images/svg-tech/selenium-original.svg"
  },
  {
    "id": "sonarqube",
    "name": "SonarQube",
    "type": "Tool",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Clean Code Quality",
    "subStatValue": "41.3%",
    "passiveName": "Static Code Analysis",
    "passiveDesc": "Inspects code vulnerabilities, code smells, and security hotspots across pipeline commits.",
    "description": "An open-source platform developed for continuous inspection of code quality.",
    "svgPath": "/assets/images/svg-tech/sonarqube-original.svg"
  },
  {
    "id": "trello",
    "name": "Trello",
    "type": "Tool",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Kanban Board",
    "subStatValue": "36.8%",
    "passiveName": "Visual Card Flow",
    "passiveDesc": "Organizes project tasks, sprint backlogs, and team workflows into visual cards.",
    "description": "A web-based, Kanban-style, list-making application.",
    "svgPath": "/assets/images/svg-tech/trello-original.svg"
  },
  {
    "id": "vitejs",
    "name": "Vite",
    "type": "Tool",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Native ESM HMR",
    "subStatValue": "44.1%",
    "passiveName": "esbuild Fast Bundler",
    "passiveDesc": "Lightning-fast Hot Module Replacement (HMR) powered by native ES modules.",
    "description": "Next Generation Frontend Tooling providing a fast dev server and bundled production assets.",
    "svgPath": "/assets/images/svg-tech/vitejs-original.svg"
  },
  {
    "id": "yarn",
    "name": "Yarn",
    "type": "Tool",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 542,
    "subStatName": "Deterministic Lockfile",
    "subStatValue": "66.2%",
    "passiveName": "Parallel Package Install",
    "passiveDesc": "Fast, reliable, and secure dependency management with offline package caching.",
    "description": "A software packaging system developed by Meta for the Node.js JavaScript runtime environment.",
    "svgPath": "/assets/images/svg-tech/yarn-original.svg"
  },
  {
    "id": "netbeans",
    "name": "Apache NetBeans",
    "type": "IDE",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Java Modular UI",
    "subStatValue": "36.8%",
    "passiveName": "Project Management",
    "passiveDesc": "Quickly edit, build, and debug Java desktop and web applications.",
    "description": "An open-source IDE for Java, PHP, HTML5, C/C++ and more.",
    "svgPath": "/assets/images/svg-tech/netbeans-original.svg"
  },
  {
    "id": "eclipse",
    "name": "Eclipse",
    "type": "IDE",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Java Compiler",
    "subStatValue": "36.8%",
    "passiveName": "Workspace Plugin System",
    "passiveDesc": "Rich plugin ecosystem for enterprise Java and C/C++ project development.",
    "description": "An open-source integrated development environment widely used for enterprise Java applications.",
    "svgPath": "/assets/images/svg-tech/eclipse-original.svg"
  },
  {
    "id": "intellij",
    "name": "IntelliJ IDEA",
    "type": "IDE",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Smart Refactoring",
    "subStatValue": "49.6%",
    "passiveName": "Deep Code Analysis",
    "passiveDesc": "Provides context-aware code completion, static inspection, and instant refactoring.",
    "description": "The premier Java and Kotlin IDE designed for developer ergonomics.",
    "svgPath": "/assets/images/svg-tech/intellij-original.svg"
  },
  {
    "id": "phpstorm",
    "name": "PhpStorm",
    "type": "IDE",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "PHP Static Analysis",
    "subStatValue": "55.1%",
    "passiveName": "Framework Integration",
    "passiveDesc": "Deep code intelligence for PHP, Symfony, Laravel, and SQL queries.",
    "description": "The Lightning-Smart PHP IDE by JetBrains.",
    "svgPath": "/assets/images/svg-tech/phpstorm-original.svg"
  },
  {
    "id": "pycharm",
    "name": "PyCharm",
    "type": "IDE",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Python Inspector",
    "subStatValue": "55.1%",
    "passiveName": "Virtualenv Manager",
    "passiveDesc": "Provides smart Python code completion, Django/Flask support, and visual debugging.",
    "description": "The Python IDE for Professional Developers by JetBrains.",
    "svgPath": "/assets/images/svg-tech/pycharm-original.svg"
  },
  {
    "id": "visualstudio",
    "name": "Visual Studio",
    "type": "IDE",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": ".NET Profiler",
    "subStatValue": "41.3%",
    "passiveName": "IntelliSense Engine",
    "passiveDesc": "Advanced debugging tools and memory profiling assist complex C++ and C# builds.",
    "description": "An integrated development environment from Microsoft for Windows and web development.",
    "svgPath": "/assets/images/svg-tech/visualstudio-original.svg"
  },
  {
    "id": "vscode",
    "name": "VS Code",
    "type": "IDE",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 542,
    "subStatName": "Extension Marketplace",
    "subStatValue": "88.2%",
    "passiveName": "Lightweight Agility",
    "passiveDesc": "Custom extensions and integrated terminal boost editing productivity by 100%.",
    "description": "A streamlined code editor with support for development operations like debugging and Git.",
    "svgPath": "/assets/images/svg-tech/vscode-original.svg"
  },
  {
    "id": "android",
    "name": "Android",
    "type": "OS",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Mobile Runtime",
    "subStatValue": "44.1%",
    "passiveName": "ART Virtual Machine",
    "passiveDesc": "Executes Dalvik bytecode natively across billions of mobile devices.",
    "description": "The open-source mobile operating system developed by Google.",
    "svgPath": "/assets/images/svg-tech/android-original.svg"
  },
  {
    "id": "debian",
    "name": "Debian",
    "type": "OS",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Linux Kernel",
    "subStatValue": "44.1%",
    "passiveName": "APT Package Stability",
    "passiveDesc": "Unshakable server stability and secure package management for cloud deployments.",
    "description": "A free operating system and Linux distribution known for extreme stability and security.",
    "svgPath": "/assets/images/svg-tech/debian-original.svg"
  },
  {
    "id": "kalilinux",
    "name": "Kali Linux",
    "type": "OS",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Cyber Security",
    "subStatValue": "44.1%",
    "passiveName": "Penetration Testing",
    "passiveDesc": "Pre-installed security auditing and vulnerability analysis toolset.",
    "description": "An open-source, Debian-derived Linux distribution designed for digital forensics and penetration testing.",
    "svgPath": "/assets/images/svg-tech/kalilinux-original.svg"
  },
  {
    "id": "linux",
    "name": "Linux (Tux)",
    "type": "OS",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "Kernel Architecture",
    "subStatValue": "44.1%",
    "passiveName": "POSIX Standard",
    "passiveDesc": "Unmatched process scheduling, memory virtualization, and open-source stability.",
    "description": "The open-source Unix-like operating system kernel powering the modern internet.",
    "svgPath": "/assets/images/svg-tech/linux-original.svg"
  },
  {
    "id": "msdos",
    "name": "MS-DOS",
    "type": "OS",
    "rarity": 3,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 354,
    "subStatName": "Retro CLI",
    "subStatValue": "28.0%",
    "passiveName": "16-bit Real Mode",
    "passiveDesc": "Legacy command-line disc operating system mechanics.",
    "description": "The classic 16-bit command-line operating system from early PC computing history.",
    "svgPath": "/assets/images/svg-tech/msdos-original.svg"
  },
  {
    "id": "windows11",
    "name": "Windows 11",
    "type": "OS",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "WSL2 Subsystem",
    "subStatValue": "55.1%",
    "passiveName": "Fluent Design System",
    "passiveDesc": "Integrated Windows Subsystem for Linux (WSL2) enabling native Linux command execution.",
    "description": "The latest major release of Microsoft’s Windows NT operating system.",
    "svgPath": "/assets/images/svg-tech/windows11-original.svg"
  },
  {
    "id": "arduino",
    "name": "Arduino",
    "type": "Hardware",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Microcontroller",
    "subStatValue": "55.1%",
    "passiveName": "GPIO Pin Control",
    "passiveDesc": "Low-level hardware pin manipulation grants physical circuit interaction capability.",
    "description": "An open-source hardware prototyping platform for building interactive electronic projects.",
    "svgPath": "/assets/images/svg-tech/arduino-original.svg"
  },
  {
    "id": "raspberrypi",
    "name": "Raspberry Pi",
    "type": "Hardware",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "ARM Single-Board",
    "subStatValue": "55.1%",
    "passiveName": "GPIO Hardware Bus",
    "passiveDesc": "Low-cost single-board computer for IoT projects, home servers, and hardware robotics.",
    "description": "A series of small single-board computers developed to promote teaching basic computer science.",
    "svgPath": "/assets/images/svg-tech/raspberrypi-original.svg"
  },
  {
    "id": "canva",
    "name": "Canva",
    "type": "Design",
    "rarity": 4,
    "refinement": 3,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Visual Assets",
    "subStatValue": "36.8%",
    "passiveName": "Drag & Drop Design",
    "passiveDesc": "Accelerates rapid graphic creation and presentation design.",
    "description": "An intuitive graphic design platform for creating visual content quickly.",
    "svgPath": "/assets/images/svg-tech/canva-original.svg"
  },
  {
    "id": "figma",
    "name": "Figma",
    "type": "Design",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 542,
    "subStatName": "UI/UX Prototyping",
    "subStatValue": "88.2%",
    "passiveName": "Vector Auto-Layout",
    "passiveDesc": "Real-time collaborative vector graphics and interactive screen component prototyping.",
    "description": "The collaborative interface design tool chosen by product designers worldwide.",
    "svgPath": "/assets/images/svg-tech/figma-original.svg"
  },
  {
    "id": "uml",
    "name": "UML",
    "type": "Design",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Class Diagram",
    "subStatValue": "41.3%",
    "passiveName": "Software Architecture Schema",
    "passiveDesc": "Standardized visualization language for software system design blueprints.",
    "description": "Unified Modeling Language for software architecture visual design.",
    "svgPath": "/assets/images/svg-tech/unifiedmodelinglanguage-original.svg"
  },
  {
    "id": "bash",
    "name": "Bash",
    "type": "Shell",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Command Automation",
    "subStatValue": "55.1%",
    "passiveName": "Shell Scripting",
    "passiveDesc": "Automates terminal command sequences and environment variables seamlessly.",
    "description": "The Unix shell and command language for Linux and macOS systems.",
    "svgPath": "/assets/images/svg-tech/bash-original.svg"
  },
  {
    "id": "powershell",
    "name": "PowerShell",
    "type": "Shell",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Object Pipeline",
    "subStatValue": "55.1%",
    "passiveName": ".NET Cmdlet Execution",
    "passiveDesc": "Passes structured .NET objects across shell pipelines rather than raw text streams.",
    "description": "A cross-platform task automation solution consisting of a command-line shell and scripting language.",
    "svgPath": "/assets/images/svg-tech/powershell-original.svg"
  },
  {
    "id": "apache",
    "name": "Apache",
    "type": "Server",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "HTTP Server",
    "subStatValue": "45.9%",
    "passiveName": ".htaccess Module",
    "passiveDesc": "Handles URL rewriting and virtual host routing with rock-solid server uptime.",
    "description": "An open-source HTTP web server powering reliable enterprise web hosting.",
    "svgPath": "/assets/images/svg-tech/apache-original.svg"
  },
  {
    "id": "tomcat",
    "name": "Apache Tomcat",
    "type": "Server",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Servlet Container",
    "subStatValue": "41.3%",
    "passiveName": "Jakarta EE Runtime",
    "passiveDesc": "Executes Java Servlets and renders JavaServer Pages (JSP) web applications.",
    "description": "An open-source implementation of the Jakarta Servlet, Jakarta Expression Language and Jakarta WebSocket technologies.",
    "svgPath": "/assets/images/svg-tech/tomcat-original.svg"
  },
  {
    "id": "nginx",
    "name": "NGINX",
    "type": "Server",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Reverse Proxy",
    "subStatValue": "55.1%",
    "passiveName": "Event-Driven Architecture",
    "passiveDesc": "Handles tens of thousands of concurrent connections with ultra-low memory footprint.",
    "description": "High-performance HTTP server, reverse proxy, and IMAP/POP3 proxy server.",
    "svgPath": "/assets/images/svg-tech/nginx-original.svg"
  },
  {
    "id": "graphql",
    "name": "GraphQL",
    "type": "Query Language",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "Declarative Fetch",
    "subStatValue": "55.1%",
    "passiveName": "Single Endpoint Schema",
    "passiveDesc": "Eliminates over-fetching by allowing clients to request exact JSON data shapes.",
    "description": "A query language for APIs and a runtime for fulfilling those queries with your existing data.",
    "svgPath": "/assets/images/svg-tech/graphql-plain.svg"
  },
  {
    "id": "json",
    "name": "JSON",
    "type": "Data Format",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Data Interchange",
    "subStatValue": "55.1%",
    "passiveName": "Lightweight Serialization",
    "passiveDesc": "Universal text format for serializing structured key-value data across network APIs.",
    "description": "JavaScript Object Notation is an open standard file format and data interchange format.",
    "svgPath": "/assets/images/svg-tech/json-original.svg"
  },
  {
    "id": "xml",
    "name": "XML",
    "type": "Data Format",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Extensible Schema",
    "subStatValue": "41.3%",
    "passiveName": "Tag Tree Hierarchy",
    "passiveDesc": "Encodes documents in a format that is both human-readable and machine-readable.",
    "description": "Extensible Markup Language defined by the W3C for data serialization.",
    "svgPath": "/assets/images/svg-tech/xml-original.svg"
  },
  {
    "id": "yaml",
    "name": "YAML",
    "type": "Data Format",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Indentation Schema",
    "subStatValue": "55.1%",
    "passiveName": "Human-Friendly Spec",
    "passiveDesc": "Clean indentation-based data serialization format widely used for CI/CD configuration files.",
    "description": "A human-friendly data serialization language for all programming languages.",
    "svgPath": "/assets/images/svg-tech/yaml-original.svg"
  },
  {
    "id": "opengl",
    "name": "OpenGL",
    "type": "Graphics API",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "GPU Pipeline",
    "subStatValue": "44.1%",
    "passiveName": "GLSL Shader Compilation",
    "passiveDesc": "Direct cross-language, cross-platform hardware-accelerated 2D and 3D rendering.",
    "description": "The most widely adopted 2D and 3D graphics API in the industry.",
    "svgPath": "/assets/images/svg-tech/opengl-original.svg"
  },
  {
    "id": "grafana",
    "name": "Grafana",
    "type": "Monitoring",
    "rarity": 4,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 510,
    "subStatName": "Metrics Dashboard",
    "subStatValue": "45.9%",
    "passiveName": "Real-time Telemetry",
    "passiveDesc": "Visualizes microservice metrics, logs, and traces with interactive real-time dashboards.",
    "description": "The open and composable observability and data visualization platform.",
    "svgPath": "/assets/images/svg-tech/grafana-original.svg"
  },
  {
    "id": "prometheus",
    "name": "Prometheus",
    "type": "Monitoring",
    "rarity": 5,
    "refinement": 4,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 608,
    "subStatName": "PromQL Time-Series",
    "subStatValue": "49.6%",
    "passiveName": "Metric Scraping Engine",
    "passiveDesc": "Pulls real-time HTTP metrics and time-series data for automated alerting.",
    "description": "An open-source systems monitoring and alerting toolkit originally built at SoundCloud.",
    "svgPath": "/assets/images/svg-tech/prometheus-original.svg"
  },
  {
    "id": "wordpress",
    "name": "WordPress",
    "type": "CMS",
    "rarity": 4,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 454,
    "subStatName": "Content Engine",
    "subStatValue": "55.1%",
    "passiveName": "Plugin Ecosystem",
    "passiveDesc": "Powers over 40% of all websites on the web with customizable themes and plugins.",
    "description": "An open-source content management system written in PHP paired with a MySQL/MariaDB database.",
    "svgPath": "/assets/images/svg-tech/wordpress-plain.svg"
  },
  {
    "id": "jetbrains",
    "name": "JetBrains",
    "type": "Tool Suite",
    "rarity": 5,
    "refinement": 5,
    "level": 90,
    "maxLevel": 90,
    "baseAtk": 674,
    "subStatName": "IDE Suite",
    "subStatValue": "44.1%",
    "passiveName": "Developer Productivity",
    "passiveDesc": "Empowers developers with intelligent IDE tools across all major programming languages.",
    "description": "Tools for software developers and teams.",
    "svgPath": "/assets/images/svg-tech/jetbrains-original.svg"
  }
];

export const EQUIPPED_WEAPON = WEAPONS_DATA.find((w) => w.isEquipped) || WEAPONS_DATA[0];
