export interface WeaponItemData {
  id: string;
  name: string;
  type: string;
  rarity: number;
  refinement: number;
  level: number;
  maxLevel: number;
  baseAtk: number;
  subStatName: string;
  subStatValue: string;
  passiveName: string;
  passiveDesc: string;
  description: string;
  svgPath: string;
  isEquipped?: boolean;
  isLocked?: boolean;
}

export const WEAPONS_DATA: WeaponItemData[] = [
  {
    id: 'react',
    name: 'React',
    type: 'Library',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 542,
    subStatName: 'Component DMG',
    subStatValue: '88.2%',
    passiveName: 'Virtual DOM Mastery',
    passiveDesc: 'Increases Render Efficiency by 80%. Re-renders occur 50% faster when state changes.',
    description: 'A component-based UI framework forged in Meta labs, capable of reactive UI rendering with unmatched precision.',
    svgPath: '/assets/images/svg-tech/react-original.svg',
    isEquipped: true,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    type: 'Language',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Type Safety',
    subStatValue: '44.1%',
    passiveName: 'Strict Type System',
    passiveDesc: 'Eliminates 95% of runtime TypeError bugs before compilation.',
    description: 'A strongly typed programming language built on JavaScript, giving developers total control over code integrity.',
    svgPath: '/assets/images/svg-tech/typescript-original.svg',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    type: 'Language',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Event Loop',
    subStatValue: '55.1%',
    passiveName: 'Async Concurrency',
    passiveDesc: 'Non-blocking I/O operations grant non-stop execution speed.',
    description: 'The ancient web scripting language powering dynamic interactions across all browser realms.',
    svgPath: '/assets/images/svg-tech/javascript-original.svg',
  },
  {
    id: 'cplusplus',
    name: 'C++',
    type: 'Language',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Raw Performance',
    subStatValue: '49.6%',
    passiveName: 'Manual Memory Control',
    passiveDesc: 'Direct pointer manipulation increases execution speed by 120%.',
    description: 'A legendary high-performance language crafted for low-level systems and graphics engines.',
    svgPath: '/assets/images/svg-tech/cplusplus-original.svg',
  },
  {
    id: 'csharp',
    name: 'C#',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: '.NET Core',
    subStatValue: '41.3%',
    passiveName: 'Garbage Collection',
    passiveDesc: 'Automatically reclaims unused memory during intense computations.',
    description: 'A versatile object-oriented language developed by Microsoft for enterprise and game development.',
    svgPath: '/assets/images/svg-tech/csharp-original.svg',
  },
  {
    id: 'java',
    name: 'Java',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'JVM Portability',
    subStatValue: '55.1%',
    passiveName: 'Write Once Run Anywhere',
    passiveDesc: 'Cross-platform compatibility protects against environment vulnerabilities.',
    description: 'A battle-tested enterprise language running on billions of devices worldwide.',
    svgPath: '/assets/images/svg-tech/java-original.svg',
  },
  {
    id: 'python',
    name: 'Python',
    type: 'Language',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Data Science',
    subStatValue: '66.2%',
    passiveName: 'Syntax Elegance',
    passiveDesc: 'Readability boosted by 100%. Accelerates prototyping speed.',
    description: 'An expressive high-level language revered for AI, machine learning, and rapid development.',
    svgPath: '/assets/images/svg-tech/python-original.svg',
  },
  {
    id: 'godot',
    name: 'Godot',
    type: 'Engine',
    rarity: 4,
    refinement: 3,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'Node System',
    subStatValue: '69.0%',
    passiveName: 'Lightweight Architecture',
    passiveDesc: 'Open-source game engine nodes boost 2D and 3D scene creation.',
    description: 'A lightweight, feature-packed open-source engine designed for independent game developers.',
    svgPath: '/assets/images/svg-tech/godot-original.svg',
  },
  {
    id: 'unity',
    name: 'Unity',
    type: 'Engine',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Cross Platform',
    subStatValue: '49.6%',
    passiveName: 'Shader Graph',
    passiveDesc: 'Real-time rendering pipeline delivers rich visual graphics.',
    description: 'An industry-standard game development platform for mobile, console, and PC titles.',
    svgPath: '/assets/images/svg-tech/unity-original.svg',
  },
  {
    id: 'php',
    name: 'PHP',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'Server Side',
    subStatValue: '55.1%',
    passiveName: 'Hypertext Preprocessor',
    passiveDesc: 'Processes web page templates rapidly for dynamic web delivery.',
    description: 'A web server scripting language powering a massive portion of the world wide web.',
    svgPath: '/assets/images/svg-tech/php-original.svg',
  },
  {
    id: 'c',
    name: 'C',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'Hardware Access',
    subStatValue: '41.3%',
    passiveName: 'Foundation Language',
    passiveDesc: 'Direct system call access grants unmatched efficiency.',
    description: 'The mother of modern programming languages, foundational to operating systems and kernels.',
    svgPath: '/assets/images/svg-tech/c-original.svg',
  },
];

export const EQUIPPED_WEAPON = WEAPONS_DATA.find((w) => w.isEquipped) || WEAPONS_DATA[0];
