export interface WeaponItemData {
  id: string;
  name: string;
  type: string;
  rarity: number;
  refinement: number;
  level: number;
  maxLevel: number;
  baseAtk: number;
  subStatName: string;
  subStatValue: string;
  passiveName: string;
  passiveDesc: string;
  description: string;
  svgPath: string;
  isEquipped?: boolean;
  isLocked?: boolean;
}

export const WEAPONS_DATA: WeaponItemData[] = [
  {
    id: 'react',
    name: 'React',
    type: 'Library',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 542,
    subStatName: 'Component DMG',
    subStatValue: '88.2%',
    passiveName: 'Virtual DOM Mastery',
    passiveDesc: 'Increases Render Efficiency by 80%. Re-renders occur 50% faster when state changes.',
    description: 'A component-based UI framework forged in Meta labs, capable of reactive UI rendering with unmatched precision.',
    svgPath: '/assets/images/svg-tech/react-original.svg',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    type: 'Language',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Type Safety',
    subStatValue: '44.1%',
    passiveName: 'Strict Type System',
    passiveDesc: 'Eliminates 95% of runtime TypeError bugs before compilation.',
    description: 'A strongly typed programming language built on JavaScript, giving developers total control over code integrity.',
    svgPath: '/assets/images/svg-tech/typescript-original.svg',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    type: 'Language',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Event Loop',
    subStatValue: '55.1%',
    passiveName: 'Async Concurrency',
    passiveDesc: 'Non-blocking I/O operations grant non-stop execution speed.',
    description: 'The ancient web scripting language powering dynamic interactions across all browser realms.',
    svgPath: '/assets/images/svg-tech/javascript-original.svg',
  },
  {
    id: 'cplusplus',
    name: 'C++',
    type: 'Language',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Raw Performance',
    subStatValue: '49.6%',
    passiveName: 'Manual Memory Control',
    passiveDesc: 'Direct pointer manipulation increases execution speed by 120%.',
    description: 'A legendary high-performance language crafted for low-level systems and graphics engines.',
    svgPath: '/assets/images/svg-tech/cplusplus-original.svg',
  },
  {
    id: 'csharp',
    name: 'C#',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: '.NET Core',
    subStatValue: '41.3%',
    passiveName: 'Garbage Collection',
    passiveDesc: 'Automatically reclaims unused memory during intense computations.',
    description: 'A versatile object-oriented language developed by Microsoft for enterprise and game development.',
    svgPath: '/assets/images/svg-tech/csharp-original.svg',
  },
  {
    id: 'java',
    name: 'Java',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'JVM Portability',
    subStatValue: '55.1%',
    passiveName: 'Write Once Run Anywhere',
    passiveDesc: 'Cross-platform compatibility protects against environment vulnerabilities.',
    description: 'A battle-tested enterprise language running on billions of devices worldwide.',
    svgPath: '/assets/images/svg-tech/java-original.svg',
    isEquipped: true,
  },
  {
    id: 'python',
    name: 'Python',
    type: 'Language',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Data Science',
    subStatValue: '66.2%',
    passiveName: 'Syntax Elegance',
    passiveDesc: 'Readability boosted by 100%. Accelerates prototyping speed.',
    description: 'An expressive high-level language revered for AI, machine learning, and rapid development.',
    svgPath: '/assets/images/svg-tech/python-original.svg',
  },
  {
    id: 'godot',
    name: 'Godot',
    type: 'Engine',
    rarity: 4,
    refinement: 3,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'Node System',
    subStatValue: '69.0%',
    passiveName: 'Lightweight Architecture',
    passiveDesc: 'Open-source game engine nodes boost 2D and 3D scene creation.',
    description: 'A lightweight, feature-packed open-source engine designed for independent game developers.',
    svgPath: '/assets/images/svg-tech/godot-original.svg',
  },
  {
    id: 'unity',
    name: 'Unity',
    type: 'Engine',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Cross Platform',
    subStatValue: '49.6%',
    passiveName: 'Shader Graph',
    passiveDesc: 'Real-time rendering pipeline delivers rich visual graphics.',
    description: 'An industry-standard game development platform for mobile, console, and PC titles.',
    svgPath: '/assets/images/svg-tech/unity-original.svg',
  },
  {
    id: 'php',
    name: 'PHP',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'Server Side',
    subStatValue: '55.1%',
    passiveName: 'Hypertext Preprocessor',
    passiveDesc: 'Processes web page templates rapidly for dynamic web delivery.',
    description: 'A web server scripting language powering a massive portion of the world wide web.',
    svgPath: '/assets/images/svg-tech/php-original.svg',
  },
  {
    id: 'c',
    name: 'C',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'Hardware Access',
    subStatValue: '41.3%',
    passiveName: 'Foundation Language',
    passiveDesc: 'Direct system call access grants unmatched efficiency.',
    description: 'The mother of modern programming languages, foundational to operating systems and kernels.',
    svgPath: '/assets/images/svg-tech/c-original.svg',
  },
  {
    id: 'angular',
    name: 'Angular',
    type: 'Framework',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'RxJS Stream',
    subStatValue: '45.9%',
    passiveName: 'Two-Way Binding',
    passiveDesc: 'Synchronizes view and model state automatically across complex application trees.',
    description: 'A robust TypeScript web framework developed by Google for enterprise single-page applications.',
    svgPath: '/assets/images/svg-tech/angular-original.svg',
  },
  {
    id: 'blender',
    name: 'Blender',
    type: 'Tool',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: '3D Sculpting',
    subStatValue: '49.6%',
    passiveName: 'Cycles Render Engine',
    passiveDesc: 'Real-time ray tracing and mesh sculpting unleash creative visual fidelity.',
    description: 'An open-source 3D creation suite supporting modeling, rigging, animation, rendering, and compositing.',
    svgPath: '/assets/images/svg-tech/blender-original.svg',
  },
  {
    id: 'css3',
    name: 'CSS3',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'Style Mastery',
    subStatValue: '55.1%',
    passiveName: 'Flexbox & Grid Alignment',
    passiveDesc: 'Mastery over layouts grants pixel-perfect responsive design capabilities.',
    description: 'The core styling language of the web, responsible for visual layouts, keyframe animations, and themes.',
    svgPath: '/assets/images/svg-tech/css3-original.svg',
  },
  {
    id: 'docker',
    name: 'Docker',
    type: 'Tool',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Containerization',
    subStatValue: '44.1%',
    passiveName: 'Isolated Environments',
    passiveDesc: 'Bundles code and dependencies into portable, isolated container images.',
    description: 'An open platform for developing, shipping, and running applications inside lightweight containers.',
    svgPath: '/assets/images/svg-tech/docker-original.svg',
  },
  {
    id: 'html5',
    name: 'HTML5',
    type: 'Language',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'DOM Structure',
    subStatValue: '55.1%',
    passiveName: 'Semantic Markup',
    passiveDesc: 'Provides structural foundation and accessible DOM element parsing.',
    description: 'The standard markup language for documents designed to be displayed in web browsers.',
    svgPath: '/assets/images/svg-tech/html5-original.svg',
  },
  {
    id: 'mysql-wordmark',
    name: 'MySQL',
    type: 'Database',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'SQL Queries',
    subStatValue: '41.3%',
    passiveName: 'Indexed Lookup',
    passiveDesc: 'Accelerates join operations across complex relational tables.',
    description: 'MySQL database insignia with full brand wordmark.',
    svgPath: '/assets/images/svg-tech/mysql-original-wordmark.svg',
  },
  {
    id: 'nodejs-wordmark',
    name: 'Node.js Logo',
    type: 'Runtime',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'NPM Ecosystem',
    subStatValue: '45.9%',
    passiveName: 'Module Resolution',
    passiveDesc: 'Instantly links package dependencies across server pipelines.',
    description: 'Node.js runtime badge featuring full wordmark branding.',
    svgPath: '/assets/images/svg-tech/nodejs-original-wordmark.svg',
  },
  {
    id: 'oracle',
    name: 'Oracle',
    type: 'Database',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Enterprise SQL',
    subStatValue: '44.1%',
    passiveName: 'PL/SQL Execution',
    passiveDesc: 'High-availability data clustering and enterprise-grade security protocols.',
    description: 'A multi-model database management system designed for mission-critical enterprise workloads.',
    svgPath: '/assets/images/svg-tech/oracle-original.svg',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    type: 'Database',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'JSONB Indexing',
    subStatValue: '49.6%',
    passiveName: 'Object-Relational Power',
    passiveDesc: 'Advanced indexing methods support complex spatial and document queries.',
    description: 'A powerful, open-source object-relational database system with a reputation for reliability.',
    svgPath: '/assets/images/svg-tech/postgresql-original.svg',
  },
  {
    id: 'postman',
    name: 'Postman',
    type: 'Tool',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'API Testing',
    subStatValue: '41.3%',
    passiveName: 'Endpoint Automation',
    passiveDesc: 'Automates REST and GraphQL request testing and documentation generation.',
    description: 'An API platform for building, testing, and iterating on web endpoints.',
    svgPath: '/assets/images/svg-tech/postman-original.svg',
  },
  {
    id: 'sass',
    name: 'Sass',
    type: 'Tool',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'SCSS Nesting',
    subStatValue: '55.1%',
    passiveName: 'Mixin Generation',
    passiveDesc: 'Reusability mixins and CSS variables reduce stylesheet duplication by 60%.',
    description: 'A mature, stable, and powerful professional-grade CSS extension language.',
    svgPath: '/assets/images/svg-tech/sass-original.svg',
  },
  {
    id: 'spring',
    name: 'Spring Boot',
    type: 'Framework',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Dependency Injection',
    subStatValue: '49.6%',
    passiveName: 'Inversion of Control',
    passiveDesc: 'Auto-configuration streamlines microservice REST backend bootstrapping.',
    description: 'An enterprise Java framework used to build standalone, production-grade Spring applications.',
    svgPath: '/assets/images/svg-tech/spring-original.svg',
  },
  {
    id: 'tailwindcss',
    name: 'Tailwind CSS',
    type: 'Framework',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 542,
    subStatName: 'Utility First',
    subStatValue: '66.2%',
    passiveName: 'JIT Compilation',
    passiveDesc: 'Just-in-Time CSS engine purges unused styles for ultra-compact bundle size.',
    description: 'A utility-first CSS framework packed with classes for rapid custom UI building.',
    svgPath: '/assets/images/svg-tech/tailwindcss-original.svg',
  },
  {
    id: 'visualstudio',
    name: 'Visual Studio',
    type: 'IDE',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: '.NET Profiler',
    subStatValue: '41.3%',
    passiveName: 'IntelliSense Engine',
    passiveDesc: 'Advanced debugging tools and memory profiling assist complex C++ and C# builds.',
    description: 'An integrated development environment from Microsoft for Windows and web development.',
    svgPath: '/assets/images/svg-tech/visualstudio-original.svg',
  },
  {
    id: 'vscode',
    name: 'VS Code',
    type: 'IDE',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 542,
    subStatName: 'Extension Marketplace',
    subStatValue: '88.2%',
    passiveName: 'Lightweight Agility',
    passiveDesc: 'Custom extensions and integrated terminal boost editing productivity by 100%.',
    description: 'A streamlined code editor with support for development operations like debugging and Git.',
    svgPath: '/assets/images/svg-tech/vscode-original.svg',
  },
  {
    id: 'vuejs',
    name: 'Vue.js',
    type: 'Framework',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 542,
    subStatName: 'Reactivity System',
    subStatValue: '66.2%',
    passiveName: 'Single File Components',
    passiveDesc: 'Ref and reactive state tracking update virtual DOM nodes efficiently.',
    description: 'A progressive JavaScript framework for building user interfaces on the web.',
    svgPath: '/assets/images/svg-tech/vuejs-original.svg',
  },
  {
    id: 'apache',
    name: 'Apache',
    type: 'Server',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'HTTP Server',
    subStatValue: '45.9%',
    passiveName: '.htaccess Module',
    passiveDesc: 'Handles URL rewriting and virtual host routing with rock-solid server uptime.',
    description: 'An open-source HTTP web server powering reliable enterprise web hosting.',
    svgPath: '/assets/images/svg-tech/apache-original.svg',
  },
  {
    id: 'arduino',
    name: 'Arduino',
    type: 'Hardware',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'Microcontroller',
    subStatValue: '55.1%',
    passiveName: 'GPIO Pin Control',
    passiveDesc: 'Low-level hardware pin manipulation grants physical circuit interaction capability.',
    description: 'An open-source hardware prototyping platform for building interactive electronic projects.',
    svgPath: '/assets/images/svg-tech/arduino-original.svg',
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    type: 'Framework',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: '12-Column Grid',
    subStatValue: '55.1%',
    passiveName: 'Pre-styled UI Components',
    passiveDesc: 'Accelerates UI wireframing with ready-to-use responsive CSS components.',
    description: 'A powerful, feature-packed frontend toolkit for fast mobile-first web layout design.',
    svgPath: '/assets/images/svg-tech/bootstrap-original.svg',
  },
  {
    id: 'flutter',
    name: 'Flutter',
    type: 'Framework',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Dart Engine',
    subStatValue: '66.2%',
    passiveName: 'Hot Reload',
    passiveDesc: 'Compiles native ARM code instantly for smooth 60fps multi-platform rendering.',
    description: 'Google’s UI toolkit for building natively compiled applications for mobile, web, and desktop from a single codebase.',
    svgPath: '/assets/images/svg-tech/flutter-original.svg',
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    type: 'Database',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'NoSQL BSON',
    subStatValue: '49.6%',
    passiveName: 'Document Sharding',
    passiveDesc: 'Flexible schema document storage allows seamless dynamic scaling across server clusters.',
    description: 'A popular document-oriented NoSQL database designed for high availability and scalability.',
    svgPath: '/assets/images/svg-tech/mongodb-original.svg',
  },
  {
    id: 'bash',
    name: 'Bash',
    type: 'Shell',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'Command Automation',
    subStatValue: '55.1%',
    passiveName: 'Shell Scripting',
    passiveDesc: 'Automates terminal command sequences and environment variables seamlessly.',
    description: 'The Unix shell and command language for Linux and macOS systems.',
    svgPath: '/assets/images/svg-tech/bash-original.svg',
  },
  {
    id: 'bun',
    name: 'Bun',
    type: 'Runtime',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Zig Performance',
    subStatValue: '44.1%',
    passiveName: 'Ultra Fast Bundler',
    passiveDesc: 'Blazing-fast JavaScript runtime, package manager, and bundler all in one.',
    description: 'An incredibly fast JavaScript runtime built with Zig for modern server-side apps.',
    svgPath: '/assets/images/svg-tech/bun-original.svg',
  },
  {
    id: 'canva',
    name: 'Canva',
    type: 'Design',
    rarity: 4,
    refinement: 3,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'Visual Assets',
    subStatValue: '36.8%',
    passiveName: 'Drag & Drop Design',
    passiveDesc: 'Accelerates rapid graphic creation and presentation design.',
    description: 'An intuitive graphic design platform for creating visual content quickly.',
    svgPath: '/assets/images/svg-tech/canva-original.svg',
  },
  {
    id: 'chartjs',
    name: 'Chart.js',
    type: 'Library',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'Canvas Data Viz',
    subStatValue: '41.3%',
    passiveName: 'Dynamic Rendering',
    passiveDesc: 'Renders responsive 2D HTML5 canvas charts dynamically from raw dataset streams.',
    description: 'Simple yet flexible JavaScript charting library for designers and developers.',
    svgPath: '/assets/images/svg-tech/chartjs-original.svg',
  },
  {
    id: 'chrome',
    name: 'Google Chrome',
    type: 'Browser',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'DevTools Suite',
    subStatValue: '55.1%',
    passiveName: 'V8 Execution Engine',
    passiveDesc: 'Provides live DOM debugging, network profiling, and Lighthouse performance auditing.',
    description: 'The dominant web browser powering modern Web APIs and developer inspect tools.',
    svgPath: '/assets/images/svg-tech/chrome-original.svg',
  },
  {
    id: 'cmake',
    name: 'CMake',
    type: 'Tool',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'Build Generation',
    subStatValue: '41.3%',
    passiveName: 'Cross-Platform Build',
    passiveDesc: 'Generates native build scripts across GCC, Clang, and MSVC platforms.',
    description: 'An open-source family of tools designed to build, test, and package C and C++ software.',
    svgPath: '/assets/images/svg-tech/cmake-original.svg',
  },
  {
    id: 'codeigniter',
    name: 'CodeIgniter',
    type: 'Framework',
    rarity: 4,
    refinement: 3,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'MVC Footprint',
    subStatValue: '36.8%',
    passiveName: 'Lightweight PHP Routing',
    passiveDesc: 'Delivers high-performance server routing with minimal configuration overhead.',
    description: 'A powerful PHP framework with a tiny footprint for building full-featured web apps.',
    svgPath: '/assets/images/svg-tech/codeigniter-plain.svg',
  },
  {
    id: 'dart',
    name: 'Dart',
    type: 'Language',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Sound Null Safety',
    subStatValue: '49.6%',
    passiveName: 'AOT Compilation',
    passiveDesc: 'Compiles directly to fast native machine code for mobile and desktop apps.',
    description: 'A client-optimized programming language developed by Google for fast multi-platform apps.',
    svgPath: '/assets/images/svg-tech/dart-original.svg',
  },
  {
    id: 'debian',
    name: 'Debian',
    type: 'OS',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Linux Kernel',
    subStatValue: '44.1%',
    passiveName: 'APT Package Stability',
    passiveDesc: 'Unshakable server stability and secure package management for cloud deployments.',
    description: 'A free operating system and Linux distribution known for extreme stability and security.',
    svgPath: '/assets/images/svg-tech/debian-original.svg',
  },
  {
    id: 'discordjs',
    name: 'Discord.js',
    type: 'Library',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'WebSocket Gateway',
    subStatValue: '55.1%',
    passiveName: 'Bot Event Handling',
    passiveDesc: 'Interacts seamlessly with the Discord API for automated community interactions.',
    description: 'A powerful Node.js module that allows developers to interact easily with the Discord API.',
    svgPath: '/assets/images/svg-tech/discordjs-original.svg',
  },
  {
    id: 'django',
    name: 'Django',
    type: 'Framework',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'Python ORM',
    subStatValue: '49.6%',
    passiveName: 'Batteries Included',
    passiveDesc: 'Built-in authentication, admin panel, and ORM accelerate secure backend creation.',
    description: 'A high-level Python web framework that encourages rapid development and clean design.',
    svgPath: '/assets/images/svg-tech/django-plain.svg',
  },
  {
    id: 'dot-net',
    name: '.NET Framework',
    type: 'Framework',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'CLR Execution',
    subStatValue: '41.3%',
    passiveName: 'Managed Code Runtime',
    passiveDesc: 'Provides memory management, security profiling, and language interoperability.',
    description: 'Microsoft’s legacy enterprise software development framework for Windows.',
    svgPath: '/assets/images/svg-tech/dot-net-original.svg',
  },
  {
    id: 'dotnetcore',
    name: '.NET Core',
    type: 'Framework',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Cross-Platform CLR',
    subStatValue: '44.1%',
    passiveName: 'High Throughput API',
    passiveDesc: 'Ultra-fast web API execution and cloud-native microservice architecture.',
    description: 'A open-source, cross-platform successor to .NET for cloud-native web services.',
    svgPath: '/assets/images/svg-tech/dotnetcore-original.svg',
  },
  {
    id: 'eclipse',
    name: 'Eclipse',
    type: 'IDE',
    rarity: 4,
    refinement: 3,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'Java Compiler',
    subStatValue: '36.8%',
    passiveName: 'Workspace Plugin System',
    passiveDesc: 'Rich plugin ecosystem for enterprise Java and C/C++ project development.',
    description: 'An open-source integrated development environment widely used for enterprise Java applications.',
    svgPath: '/assets/images/svg-tech/eclipse-original.svg',
  },
  {
    id: 'electron',
    name: 'Electron',
    type: 'Framework',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 542,
    subStatName: 'Chromium Bridge',
    subStatValue: '66.2%',
    passiveName: 'Desktop IPC Bridge',
    passiveDesc: 'Build cross-platform desktop apps using web technologies like HTML, CSS, and JS.',
    description: 'A framework for creating native desktop applications using web technologies.',
    svgPath: '/assets/images/svg-tech/electron-original.svg',
  },
  {
    id: 'eslint',
    name: 'ESLint',
    type: 'Tool',
    rarity: 4,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'AST Analysis',
    subStatValue: '55.1%',
    passiveName: 'Static Code Linting',
    passiveDesc: 'Enforces code style and catches syntax/logical bugs before runtime compilation.',
    description: 'A pluggable static analysis tool for identifying problematic patterns in JavaScript code.',
    svgPath: '/assets/images/svg-tech/eslint-original.svg',
  },
  {
    id: 'express',
    name: 'Express.js',
    type: 'Framework',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'REST Middleware',
    subStatValue: '55.1%',
    passiveName: 'Minimalist Server Routing',
    passiveDesc: 'High-speed HTTP routing and custom middleware pipeline execution.',
    description: 'A fast, unopinionated, minimalist web framework for Node.js backends.',
    svgPath: '/assets/images/svg-tech/express-original.svg',
  },
  {
    id: 'figma',
    name: 'Figma',
    type: 'Design',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 542,
    subStatName: 'UI/UX Prototyping',
    subStatValue: '88.2%',
    passiveName: 'Vector Auto-Layout',
    passiveDesc: 'Real-time collaborative vector graphics and interactive screen component prototyping.',
    description: 'The collaborative interface design tool chosen by product designers worldwide.',
    svgPath: '/assets/images/svg-tech/figma-original.svg',
  },
  {
    id: 'filezilla',
    name: 'FileZilla',
    type: 'Tool',
    rarity: 4,
    refinement: 3,
    level: 90,
    maxLevel: 90,
    baseAtk: 454,
    subStatName: 'FTP Protocol',
    subStatValue: '36.8%',
    passiveName: 'SFTP File Transfer',
    passiveDesc: 'Transfers website files securely to remote hosting servers.',
    description: 'A free, cross-platform FTP, FTPS and SFTP client with a clean GUI interface.',
    svgPath: '/assets/images/svg-tech/filezilla-original.svg',
  },
  {
    id: 'github',
    name: 'GitHub',
    type: 'Platform',
    rarity: 5,
    refinement: 5,
    level: 90,
    maxLevel: 90,
    baseAtk: 674,
    subStatName: 'Git Versioning',
    subStatValue: '44.1%',
    passiveName: 'CI/CD Actions Flow',
    passiveDesc: 'Automates cloud builds, code reviews, and global open-source repository hosting.',
    description: 'The world’s leading developer platform for code hosting, version control, and collaboration.',
    svgPath: '/assets/images/svg-tech/github-original.svg',
  },
  {
    id: 'gitkraken',
    name: 'GitKraken',
    type: 'Tool',
    rarity: 4,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 510,
    subStatName: 'Branch Visualizer',
    subStatValue: '41.3%',
    passiveName: 'Git Tree Graph',
    passiveDesc: 'Simplifies complex merge conflicts and branch rebase operations visually.',
    description: 'A powerful, intuitive, cross-platform GUI client for Git version control.',
    svgPath: '/assets/images/svg-tech/gitkraken-original.svg',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    type: 'Platform',
    rarity: 5,
    refinement: 4,
    level: 90,
    maxLevel: 90,
    baseAtk: 608,
    subStatName: 'DevOps Pipeline',
    subStatValue: '49.6%',
    passiveName: 'Auto DevOps CI',
    passiveDesc: 'Integrates security scanning, code hosting, and automated deployment pipelines.',
    description: 'The complete DevOps platform delivered as a single application.',
    svgPath: '/assets/images/svg-tech/gitlab-original.svg',
  },
];

export const EQUIPPED_WEAPON = WEAPONS_DATA.find((w) => w.isEquipped) || WEAPONS_DATA[0];
